name: Status Check Functions
on:
  - push

jobs:
    job-1:
        runs-on: ubuntu-latest
        steps:
            - name: Step 1
              run: sleep 20
            - name: Runs on Failure
              if: failure()
              run: echo 'Runs only on failure'
            - name: Runs on Success
                # This is not necessary, as the job will run only if the previous step is successful
              if: success()
              run: echo 'Runs only on success'
            - name: Always Runs
              if: always()
              run: echo 'Always runs'
            - name: Runs on Cancel
              if: cancelled()
              run: echo 'Runs only on cancel'

    job-2:
        runs-on: ubuntu-latest
        needs: job-1
        if: success()
        steps:
            - run: echo 'Job 2'
